# Build Docker images and push them to docker hub

name: Dockerize Orchestrator

#on:
#  push:
#    branches: [ "main" ] # Runs on merge

on:
  workflow_dispatch:

env:
  IMAGE_NAME: orchestrator
  SHORT_SHA: ${{ github.sha.substr(0, 8) }}

jobs:
  # ARM64 build job
  arm64:
    runs-on: ubuntu-24.04-arm
    env:
      DOCKER_TARGET_PLATFORM: linux/arm64
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build ARM Docker image
        run: |
          set -euo pipefail
          docker build --push --platform linux/arm64 \
            --build-arg BUILD_IMAGE_TAG=9.0-noble-arm64v8 \
            --build-arg RUN_IMAGE_TAG=9.0-alpine-arm64v8 \
            --tag "${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}-arm64" .

  # AMD64 build job
  amd64:
    runs-on: ubuntu-latest
    needs: arm64  # Wait for ARM64 job to finish
    env:
      DOCKER_TARGET_PLATFORM: linux/amd64
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build AMD Docker image
        run: |
          set -euo pipefail
          docker build --push --platform linux/amd64 \
            --build-arg BUILD_IMAGE_TAG=9.0-noble-amd64 \
            --build-arg RUN_IMAGE_TAG=9.0-alpine-amd64 \
            --tag "${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}-amd64" .

  # Multi-arch manifests
  multiarch:
    runs-on: ubuntu-latest
    needs:
      - arm64
      - amd64
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and publish multi-arch manifests
        run: |
          set -euo pipefail

          USER=${{ vars.DOCKERHUB_USERNAME }}
          NAME=${{ env.IMAGE_NAME }}
          TAG=${{ env.SHORT_SHA }}

          # Pull platform-specific images
          docker pull --platform linux/amd64 "$USER/$NAME:$TAG-amd64"
          docker pull --platform linux/arm64 "$USER/$NAME:$TAG-arm64"

          # Create and publish "latest" tag
          docker manifest create "$USER/$NAME:latest" "$USER/$NAME:$TAG-amd64" "$USER/$NAME:$TAG-arm64"
          docker manifest push "$USER/$NAME:latest"

          # Create and publish "short SHA" tag
          docker manifest create "$USER/$NAME:$SHORT" "$USER/$NAME:$TAG-amd64" "$USER/$NAME:$TAG-arm64"
          docker manifest push "$USER/$NAME:$TAG"
